### ISSUE TITLE
How to reduce entry.js size when p5vue used in my project?

### ISSUE THREAD

**Issue by davinma** [Nico-Mayer/p5vue#3]
<img width="477" alt="image" src="https://github.com/Nico-Mayer/p5vue/assets/2345776/54de5b73-03cc-4cd7-a0b8-d30305e30642">
<img width="788" alt="image" src="https://github.com/Nico-Mayer/p5vue/assets/2345776/e3b4144e-27dc-4c45-9449-ae6209bfbe47">

I got warning like this:

> (!) Some chunks are larger than 500 kBs after minification. Consider:
> - Using dynamic import() to code-split the application
> - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
> - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

Thank for your p5vue❤️

**Comment by Nico-Mayer** [comment]
Hello @davinma, thanks for reaching out! I'm currently immersed in college commitments, which limits my immediate ability to thoroughly investigate the issue. From my initial assessment, it appears that the larger bundle size might be linked to p5vue bundling p5js by default. Feel free to use the current setup, and if you wish to contribute, the project is open for pull requests. 
Appreciate your understanding!

**Comment by davinma** [comment]
Okay, have a good college time :-)
